networks:
    poc-network:   # Must match your Docker Compose network
      name: poc-network

services:
  postgres:
    image: postgres:14
    container_name: poc-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=prefect
    volumes:
      - /home/adithya/workspace/prefect_poc_storage/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - poc-network

  prefect-server:
    image: prefecthq/prefect:3.4.9-python3.12
    container_name: prefect-server
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_LOGGING_LEVEL=INFO
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:1234@postgres:5432/prefect
    ports:
      - "4200:4200"
    volumes:
      - /home/adithya/workspace/prefect_storage/prefect_poc_data:/root/.prefect
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "
        echo 'Installing prefect-docker packages...' &&
        pip install prefect-docker==0.6.6 &&
        prefect server start --host 0.0.0.0
      "
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:4200/api/health')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - poc-network

  prefect-workpool-init:
    image: prefecthq/prefect:3.4.13-python3.12
    container_name: prefect-workpool-init
    depends_on:
      prefect-server:
        condition: service_healthy
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - MOUNTPATH=${MOUNTPATH}
      - DOCKER_REGISTRY_USER=${DOCKER_REGISTRY_USER}
      - DOCKER_REGISTRY_PASSWORD=${DOCKER_REGISTRY_PASSWORD}
      - DOCKER_REGISTRY_URL=${DOCKER_REGISTRY_URL}
      - PREFECT_NETWORK=poc-network
    volumes:
      - ../workpool_config:/opt/scripts/
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -c "
        pip install tabulate==0.9.0 && pip install prefect-docker==0.6.6 &&
        echo 'Setting up work pools using Python script...' &&
        python /opt/scripts/create_workpools.py
      "
    networks:
      - poc-network

  poc-worker:
    image: prefecthq/prefect:3.4.13-python3.12
    container_name: cron-worker
    depends_on:
      prefect-workpool-init:
        condition: service_completed_successfully
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PREFECT_LOGGING_LEVEL=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -c "
        echo 'Installing prefect-docker prefect-gitlab packages...' &&
        pip install prefect-docker prefect-gitlab &&
        echo 'Starting worker for cron-worker...' &&
        prefect worker start --pool poc-pool
      "
    healthcheck:
      test: ["CMD-SHELL", "prefect work-pool inspect poc-pool"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - poc-network

volumes:
  postgres_data:
  prefect_poc_data:
